name: ish_top
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.17.2
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.20
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.5
  lottie: ^3.1.0
  easy_localization: ^3.0.0
  image_picker: ^1.0.7
  firebase_storage: ^11.7.4
  zoom_tap_animation: ^1.1.0
  flutter_screenutil: ^5.9.0
  mask_text_input_formatter: ^2.9.0
  easy_image_viewer: ^1.5.0
  image: ^3.0.1
  flutter_multi_formatter: ^2.12.8
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
  bloc_concurrency: ^0.2.5
  url_launcher: ^6.2.6
  flutter_phone_direct_caller: ^2.1.1
  vibration: ^1.8.4
  fluttertoast: ^8.2.5
  carousel_slider: ^4.2.1
  add_2_calendar: ^3.0.1
  social_media_recorder: ^1.1.13
  google_maps_flutter: ^2.6.1
  alarm: ^3.1.4
  page_transition: ^2.1.0
  video_player: ^2.8.6
  pinput: ^4.0.0
  photo_view: ^0.15.0
  timeago: ^3.6.1


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/
    - assets/audios/
    - assets/translations/
    - assets/videos/
