name: ish_top
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  firebase_core: ^2.32.0
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.17.5
  simple_circular_progress_bar: ^1.0.2
  firebase_messaging: ^14.9.4
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  easy_localization: ^3.0.7
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  flutter_screenutil: ^5.9.3
  mask_text_input_formatter: ^2.9.0
  easy_image_viewer: ^1.5.0
  image: ^4.2.0
  flutter_multi_formatter: ^2.12.8
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
  bloc_concurrency: ^0.2.5
  url_launcher: ^6.3.0
  flutter_phone_direct_caller: ^2.1.1
  vibration: ^1.9.0
  fluttertoast: ^8.2.6
  carousel_slider: ^4.2.1
  add_2_calendar: ^3.0.1
  social_media_recorder: ^1.1.13
  google_maps_flutter: ^2.7.0
  alarm: ^3.1.4
  rive: ^0.13.8
  page_transition: ^2.1.0
  video_player: ^2.8.7
  pinput: ^5.0.0
  photo_view: ^0.15.0
  timeago: ^3.6.1
  http: ^1.2.2
  geolocator: ^12.0.0
  yandex_geocoder: ^2.3.1
  geocoding: ^3.0.0
  location: ^6.0.2
  modal_bottom_sheet: ^3.0.0
  animations: ^2.0.11
  pull_down_button: ^0.9.4
  google_maps_flutter_ios: ^2.7.0
  dio: ^5.4.3+1
  flutter_chat_bubble: ^2.0.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1



dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/
    - assets/audios/
    - assets/rives/
    - assets/translations/
  fonts:
    - family: My
      fonts:
        - asset: assets/fonts/My.ttf
